<a href="https://colab.research.google.com/github/kurrnia/Dicoding/blob/main/dicoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Menggunakan Model untuk Melakukan Prediksi

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [ ]:
xs = np.array([1.0,  2.0, 3.0, 4.0, 5.0, 6.0], dtype=float)
ys = np.array([4.0, 6.0, 8.0, 10.0, 12.0, 14.0], dtype=float)

In [ ]:
model = tf.keras.Sequential([keras.layers.Dense(units=1, input_shape=[1]), keras.layers.Dense(units=8), keras.layers.Dense(units=1)])

In [ ]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [ ]:
model.fit(xs, ys, epochs=150)

Epoch 1/150
1/1 [==============================] - 0s 327ms/step - loss: 120.2007
Epoch 2/150
1/1 [==============================] - 0s 8ms/step - loss: 3.3187
Epoch 3/150
1/1 [==============================] - 0s 7ms/step - loss: 10.3262
Epoch 4/150
1/1 [==============================] - 0s 6ms/step - loss: 42.1519
Epoch 5/150
1/1 [==============================] - 0s 7ms/step - loss: 1.1450
Epoch 6/150
1/1 [==============================] - 0s 6ms/step - loss: 3.6978
Epoch 7/150
1/1 [==============================] - 0s 6ms/step - loss: 9.6565
Epoch 8/150
1/1 [==============================] - 0s 6ms/step - loss: 36.7771
Epoch 9/150
1/1 [==============================] - 0s 7ms/step - loss: 1.1608
Epoch 10/150
1/1 [==============================] - 0s 6ms/step - loss: 3.9118
Epoch 11/150
1/1 [==============================] - 0s 6ms/step - loss: 9.1869
Epoch 12/150
1/1 [==============================] - 0s 10ms/step - loss: 33.7679
Epoch 13/150
1/1 [==============================] - 

In [ ]:
print(model.predict([10.0]))

1/1 [==============================] - 0s 65ms/step
[[24.896038]]


## Membuat Model untuk Klasifikasi Dua Kelas

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks/Dicoding py')

Mounted at /content/drive


In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Dicoding py/citrus.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10000 non-null  object 
 1   diameter  10000 non-null  float64
 2   weight    10000 non-null  float64
 3   red       10000 non-null  int64  
 4   green     10000 non-null  int64  
 5   blue      10000 non-null  int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [ ]:
df.head()

name  diameter  weight  red  green  blue
0  orange      2.96   86.76  172     85     2
1  orange      3.91   88.05  166     78     3
2  orange      4.42   95.17  156     81     2
3  orange      4.47   95.60  163     81     4
4  orange      4.48   95.76  161     72     9

In [ ]:
df.name[df.name == 'orange'] = 0
df.name[df.name == 'grapefruit'] = 1

<ipython-input-21-e9c3e7476411>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.name[df.name == 'orange'] = 0
<ipython-input-21-e9c3e7476411>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.name[df.name == 'grapefruit'] = 1


In [ ]:
dataset = df.values

In [ ]:
X = dataset[:,1:6]

In [ ]:
y = dataset[:,0]

In [ ]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.        , 0.        , 0.74025974, 0.63529412, 0.        ],
       [0.07042254, 0.00738197, 0.66233766, 0.55294118, 0.01851852],
       [0.10822832, 0.04812589, 0.53246753, 0.58823529, 0.        ],
       ...,
       [0.93624907, 0.97133047, 0.68831169, 0.6       , 0.33333333],
       [0.96071164, 0.99216023, 0.35064935, 0.48235294, 0.16666667],
       [1.        , 1.        , 0.48051948, 0.50588235, 0.        ]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

In [ ]:
import numpy as np

Y_train = Y_train.astype(np.float32)
Y_test = Y_test.astype(np.float32)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential([    
                    Dense(32, activation='relu', input_shape=(5,)),    
                    Dense(32, activation='relu'),    
                    Dense(1, activation='sigmoid'),])

In [ ]:
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, Y_train, epochs=10)

Epoch 1/10
219/219 [==============================] - 1s 2ms/step - loss: 0.6629 - accuracy: 0.7746
Epoch 2/10
219/219 [==============================] - 0s 2ms/step - loss: 0.5960 - accuracy: 0.9087
Epoch 3/10
219/219 [==============================] - 0s 2ms/step - loss: 0.5197 - accuracy: 0.9177
Epoch 4/10
219/219 [==============================] - 0s 2ms/step - loss: 0.4253 - accuracy: 0.9239
Epoch 5/10
219/219 [==============================] - 0s 2ms/step - loss: 0.3373 - accuracy: 0.9247
Epoch 6/10
219/219 [==============================] - 0s 2ms/step - loss: 0.2768 - accuracy: 0.9239
Epoch 7/10
219/219 [==============================] - 0s 2ms/step - loss: 0.2407 - accuracy: 0.9249
Epoch 8/10
219/219 [==============================] - 0s 2ms/step - loss: 0.2196 - accuracy: 0.9257
Epoch 9/10
219/219 [==============================] - 0s 2ms/step - loss: 0.2071 - accuracy: 0.9246
Epoch 10/10
219/219 [==============================] - 0s 2ms/step - loss: 0.1994 - accuracy: 0.9259

In [ ]:
model.evaluate(X_test, Y_test)

94/94 [==============================] - 0s 1ms/step - loss: 0.1841 - accuracy: 0.9320


[0.18411985039710999, 0.9319999814033508]

## Membuat dan Melatih Model untuk Klasifikasi Banyak Kelas

In [1]:
# import library yang akan digunakan
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

In [2]:
# berfungsi untuk memanggil dataset dari gdrive
from google.colab import drive
drive.mount('/content/drive')
import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks/Dicoding py')

Mounted at /content/drive


In [3]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Dicoding py/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
df = df.drop(columns='Id')

In [6]:
category = pd.get_dummies(df.Species)
category

Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

In [7]:
new_df = pd.concat([df, category], axis=1)
new_df = new_df.drop(columns='Species')
new_df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Iris-setosa  \
0              5.1           3.5            1.4           0.2            1   
1              4.9           3.0            1.4           0.2            1   
2              4.7           3.2            1.3           0.2            1   
3              4.6           3.1            1.5           0.2            1   
4              5.0           3.6            1.4           0.2            1   
..             ...           ...            ...           ...          ...   
145            6.7           3.0            5.2           2.3            0   
146            6.3           2.5            5.0           1.9            0   
147            6.5           3.0            5.2           2.0            0   
148            6.2           3.4            5.4           2.3            0   
149            5.9           3.0            5.1           1.8            0   

     Iris-versicolor  Iris-virginica  
0                  0               0  
1                  0               0  
2                  0               0  
3                  0               0  
4                  0               0  
..               ...             ...  
145                0               1  
146                0               1  
147                0               1  
148                0               1  
149                0               1  

[150 rows x 7 columns]

In [8]:
dataset = new_df.values
dataset

array([[5.1, 3.5, 1.4, ..., 1. , 0. , 0. ],
       [4.9, 3. , 1.4, ..., 1. , 0. , 0. ],
       [4.7, 3.2, 1.3, ..., 1. , 0. , 0. ],
       ...,
       [6.5, 3. , 5.2, ..., 0. , 0. , 1. ],
       [6.2, 3.4, 5.4, ..., 0. , 0. , 1. ],
       [5.9, 3. , 5.1, ..., 0. , 0. , 1. ]])

In [9]:
# m3milih 4 kolom pertama untuk dijadikan sebagai atribut
X = dataset[:,0:4]
# memilih 3 kolom terakhir sebagai label
y = dataset[:,4:7]

In [10]:
# normalize
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [11]:
X_train, X_test, Y_test, Y_train = train_test_split(X_scale, y, test_size=0.3)

In [17]:
model = Sequential([    
                    Dense(64, activation='relu', input_shape=(4,)),    
                    Dense(64, activation='relu'),    
                    Dense(3, activation='sigmoid'),])

In [18]:
model.compile(optimizer='Adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [21]:
hist = model.fit(X_train, Y_train, epochs=100)

ValueError: ignored